services:
    sylius.exporter.spreadsheet_writer_factory:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\PortSpreadsheetWriterFactory

    sylius.exporter.spreadsheet_writer:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\SpreadsheetWriter
        arguments:
            - '@sylius.exporter.spreadsheet_writer_factory'

    # Spreadsheet-Exporters
    sylius.exporter.countries.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.countries"
            - ["Id", "Code" ,"Enabled"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.country, format: xlsx }

    sylius.exporter.shipments.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.shipments_inpost"
            - ["Odbiorca", "Imię i Nazwisko", "Telefon", "Email", "Adres*", "Miasto*", "Kod pocztowy*", "Kraj", "Liczba paczek*", "Waga paczki*", "Pobranie", "Ubezpieczenie", "Uwagi", "Referencja"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.shipment, format: xlsx }

    sylius.exporter.payments.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.payments"
            - ["Numer zamówienia", "Email", "Data płatności", "Przedmioty total", "Wysyłka total", "Zamówienie total", "Zawartość", "NIP"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.payment, format: xlsx }

    sylius.exporter.orders.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.orders"
            - ["Numer", "Status", "Produkty", "Sztuki total", "Waga total", "Total", "Total produkty", "Total wysyłka", "Waluta", "Data", "Checkout status", "Status płatności", "Status wysyłki", "Token", "Email", "Imię i nazwisko", "Firma", "Nip", "Telefon", "Ulica", "Kod pocztowy", "Miasto", "Wysyłka imie i nazwisko", "Wysyłka firma", "Wysyłka telefon", "Wysyłka ulica", "Wysyłka kod pocztowy", "Wysyłka miasto" , "Customer_ip", "Uwagi"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.order, format: xlsx }

    sylius.exporter.customers.xlsx:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.spreadsheet_writer"
            - "@sylius.exporter.pluginpool.customers"
            - ["Email", "Email_canonical", "First_name" , "Last_name" ,  "Birthday", "Gender", "Phone_number", "Subscribed_to_newsletter"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.customer, format: xlsx }
