services:
    sylius.inpostcsv_writer:
        class: Port\Csv\CsvWriter
        arguments:
            - ','

    sylius.exporter.inpostcsv_writer:
        class: FriendsOfSylius\SyliusImportExportPlugin\Writer\CsvWriter
        arguments:
            - '@sylius.inpostcsv_writer'

    sylius.exporter.shipments.inpostcsv:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporter
        arguments:
            - "@sylius.exporter.inpostcsv_writer"
            - "@sylius.exporter.pluginpool.shipments"
            - ["Firma", "Imię i Nazwisko", "Ulica", "Kod pocztowy", "Miasto", "Telefon", "Email", "Waga", "Zawartość"]
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.shipment, format: inpostcsv }
